//
// PrefsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import PromiseKit



open class PrefsAPI {
    /**
     storePushNotifyToken prefs
     
     - parameter string: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func prefsStorePushNotifyToken(string: String, completion: @escaping ((_ data: Bool?,_ error: Error?) -> Void)) {
        prefsStorePushNotifyTokenWithRequestBuilder(string: string).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     storePushNotifyToken prefs
     
     - parameter string: (body)  
     - returns: Promise<Bool>
     */
    open class func prefsStorePushNotifyToken( string: String) -> Promise<Bool> {
        let (promise, resolver) = Promise<Bool>.pending()
        prefsStorePushNotifyToken(string: string) { data, error in
            if let error = error {
                resolver.reject(error)
            } else {
                resolver.fulfill(data!)
            }
        }
        return promise
    }

    /**
     storePushNotifyToken prefs
     - POST /prefs/updatePnToken
     - update APNS token for user
     - examples: [{contentType=application/json, example=true}]
     
     - parameter string: (body)  

     - returns: RequestBuilder<Bool> 
     */
    open class func prefsStorePushNotifyTokenWithRequestBuilder(string: String) -> RequestBuilder<Bool> {
        let path = "/prefs/updatePnToken"
        let URLString = NmgApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: string)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Bool>.Type = NmgApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
