//
// AddResponseBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** AddResponseBody result type (default view) */

public struct AddResponseBody: Codable {

    public var DOB: String?
    public var avatarURL: String?
    public var email: String?
    public var handle: String?
    public var phone: String?

    public init(DOB: String?, avatarURL: String?, email: String?, handle: String?, phone: String?) {
        self.DOB = DOB
        self.avatarURL = avatarURL
        self.email = email
        self.handle = handle
        self.phone = phone
    }


}

