//
// AddRequestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AddRequestBody: Codable {

    /** Email Address */
    public var email: String?
    /** User ID */
    public var userID: String?

    public init(email: String?, userID: String?) {
        self.email = email
        self.userID = userID
    }

    public enum CodingKeys: String, CodingKey { 
        case email = "Email"
        case userID = "UserID"
    }


}

