//
// CancelRequestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CancelRequestBody: Codable {

    /** Arg 1 */
    public var arg1: String?
    /** Arg 2 */
    public var arg2: String?
    /** Arg 3 */
    public var arg3: Bool?
    /** Request Sub Type */
    public var requestSubType: String
    /** Request Type */
    public var requestType: String
    /** User ID */
    public var userID: String

    public init(arg1: String?, arg2: String?, arg3: Bool?, requestSubType: String, requestType: String, userID: String) {
        self.arg1 = arg1
        self.arg2 = arg2
        self.arg3 = arg3
        self.requestSubType = requestSubType
        self.requestType = requestType
        self.userID = userID
    }


}

