//
// HistoryRequestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HistoryRequestBody: Codable {

    public enum ConstraintMode: String, Codable { 
        case market = "market"
        case limit = "limit"
        case liquidate = "liquidate"
        case other = "other"
    }
    public enum ExecMode: String, Codable { 
        case buy = "buy"
        case sell = "sell"
        case cancelOrder = "cancel_order"
        case fundAccount = "fund_account"
        case cashOut = "cash_out"
    }
    /** Transaction Type */
    public var constraintMode: ConstraintMode?
    /** User ID */
    public var eventId: String
    /** Trade Type */
    public var execMode: ExecMode?
    /** Team ID */
    public var teamId: String?
    /** User ID */
    public var userId: String

    public init(constraintMode: ConstraintMode?, eventId: String, execMode: ExecMode?, teamId: String?, userId: String) {
        self.constraintMode = constraintMode
        self.eventId = eventId
        self.execMode = execMode
        self.teamId = teamId
        self.userId = userId
    }


}

