//
// HistoryMsgResponseBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Order &amp; Team history (default view) */

public struct HistoryMsgResponseBody: Codable {

    /** dateTime */
    public var dateTime: String
    /** description */
    public var _description: String
    /** other team ID played (if game) or event */
    public var otherID: String
    /** teamID for this row */
    public var teamID: String
    /** total transaction amt or 0 for team state-transition event */
    public var total: Int64
    /** trans ID */
    public var transID: Int64
    /** row-type; buy, sell or enum.TeamStatus.String */
    public var type: String

    public init(dateTime: String, _description: String, otherID: String, teamID: String, total: Int64, transID: Int64, type: String) {
        self.dateTime = dateTime
        self._description = _description
        self.otherID = otherID
        self.teamID = teamID
        self.total = total
        self.transID = transID
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case dateTime
        case _description = "description"
        case otherID
        case teamID
        case total
        case transID
        case type
    }


}

