//
// HistoryMsgResponseBodyCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** HistoryMsgResponseBodyCollection is the result type for an array of HistoryMsgResponseBody (default view) */
public typealias HistoryMsgResponseBodyCollection = [HistoryMsgResponseBody]
