//
// ListResponseBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ListResponseBody result type (default view) */

public struct ListResponseBody: Codable {

    /** Processing results (bot or quoted */
    public var orderResults: [OrderResultsMsg]

    public init(orderResults: [OrderResultsMsg]) {
        self.orderResults = orderResults
    }


}

