//
// NewsResultsResponseBodyCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NewsResultsResponseBodyCollection is the result type for an array of NewsResultsResponseBody (default view) */
public typealias NewsResultsResponseBodyCollection = [NewsResultsResponseBody]
