//
// OrderResultsMsg.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An incoming transaction (buy/sell order) */

public struct OrderResultsMsg: Codable {

    public enum ConstraintMode: String, Codable { 
        case market = "market"
        case limit = "limit"
        case liquidate = "liquidate"
        case other = "other"
    }
    public enum ExecMode: String, Codable { 
        case buy = "buy"
        case sell = "sell"
        case cancelOrder = "cancel_order"
        case fundAccount = "fund_account"
        case cashOut = "cash_out"
    }
    /** Client UUID */
    public var clientID: String?
    /** OrderConstraintMode */
    public var constraintMode: ConstraintMode?
    /** At what cost */
    public var cost: Float?
    /** Transaction Execution mode */
    public var execMode: ExecMode?
    /** Shares to buy or sell */
    public var shares: Int?
    /** bought or quoted */
    public var status: String?
    /** Server Transaction ID */
    public var transID: Int64?

    public init(clientID: String?, constraintMode: ConstraintMode?, cost: Float?, execMode: ExecMode?, shares: Int?, status: String?, transID: Int64?) {
        self.clientID = clientID
        self.constraintMode = constraintMode
        self.cost = cost
        self.execMode = execMode
        self.shares = shares
        self.status = status
        self.transID = transID
    }


}

