//
// PortfolioHoldingResultMsgResponseBodyCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** PortfolioHoldingResultMsgResponseBodyCollection is the result type for an array of PortfolioHoldingResultMsgResponseBody (default view) */
public typealias PortfolioHoldingResultMsgResponseBodyCollection = [PortfolioHoldingResultMsgResponseBody]
