//
// RedeemSharesRequestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RedeemSharesRequestBody: Codable {

    /** asset Key */
    public var assetKey: String?
    public var atts: FundsXferScheduleRequestBody?
    /** share quantity */
    public var shareCount: Int64?

    public init(assetKey: String?, atts: FundsXferScheduleRequestBody?, shareCount: Int64?) {
        self.assetKey = assetKey
        self.atts = atts
        self.shareCount = shareCount
    }


}

