//
// SubmitRequestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubmitRequestBody: Codable {

    public enum ConstraintMode: String, Codable { 
        case market = "market"
        case limit = "limit"
        case liquidate = "liquidate"
        case other = "other"
    }
    public enum ExecMode: String, Codable { 
        case buy = "buy"
        case sell = "sell"
        case cancelOrder = "cancel_order"
        case fundAccount = "fund_account"
        case cashOut = "cash_out"
    }
    /** All or None */
    public var allOrNone: Bool?
    public var assetKey: String
    /** Client UUID */
    public var clientID: String
    /** OrderConstraintMode */
    public var constraintMode: ConstraintMode?
    /** Transaction Execution mode */
    public var execMode: ExecMode
    /** 0 or NMG Dollars (if limit order */
    public var limitDollars: Float?
    /** Portfolio Asset Key */
    public var quotedPrice: Float
    /** Shares to buy or sell */
    public var shares: Int
    /** Server Transaction ID */
    public var transID: Int64?

    public init(allOrNone: Bool?, assetKey: String, clientID: String, constraintMode: ConstraintMode?, execMode: ExecMode, limitDollars: Float?, quotedPrice: Float, shares: Int, transID: Int64?) {
        self.allOrNone = allOrNone
        self.assetKey = assetKey
        self.clientID = clientID
        self.constraintMode = constraintMode
        self.execMode = execMode
        self.limitDollars = limitDollars
        self.quotedPrice = quotedPrice
        self.shares = shares
        self.transID = transID
    }


}

