//
// SummaryElementResponseBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Summary of one team (currently owned) inside an event */

public struct SummaryElementResponseBody: Codable {

    /** team id */
    public var teamID: String?
    /** amt spent to buy above shares in cents */
    public var totalCostBasis: Int64?
    /** shares owned in this event */
    public var totalShares: Int64?

    public init(teamID: String?, totalCostBasis: Int64?, totalShares: Int64?) {
        self.teamID = teamID
        self.totalCostBasis = totalCostBasis
        self.totalShares = totalShares
    }


}

