//
// SummarymsgResponseBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Rollup of team-position totals across entire event (default view) */

public struct SummarymsgResponseBody: Codable {

    /** unique e-id */
    public var eventID: String?
    /** event name */
    public var eventName: String?
    /** Details of each team owned in event */
    public var positions: [SummaryElementResponseBody]?

    public init(eventID: String?, eventName: String?, positions: [SummaryElementResponseBody]?) {
        self.eventID = eventID
        self.eventName = eventName
        self.positions = positions
    }


}

