//
// SummarymsgResponseBodyCollection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** SummarymsgResponseBodyCollection is the result type for an array of SummarymsgResponseBody (default view) */
public typealias SummarymsgResponseBodyCollection = [SummarymsgResponseBody]
